PRCP-1003-Customer Transaction Prediction

Problem Statement

Task 1:-Prepare a complete data analysis report on the given data.

Task 2:-Create a predictive model which will help the bank to identify which customer will make transactions in future.

In [88]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,classification_report

In [20]:
# Load the data Set 
data = pd.read_csv("train(1).csv")

In [21]:
data.head()

,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
0,train_0,0,8.9255,-6.7863,11.9081,5.0930,11.4607,-9.2834,5.1187,18.6266,...,4.4354,3.9642,3.1364,1.6910,18.5227,-2.3978,7.8784,8.5635,12.7803,-1.0914
1,train_1,0,11.5006,-4.1473,13.8588,5.3890,12.3622,7.0433,5.6208,16.5338,...,7.6421,7.7214,2.5837,10.9516,15.4305,2.0339,8.1267,8.7889,18.3560,1.9518
2,train_2,0,8.6093,-2.7457,12.0805,7.8928,10.5825,-9.0837,6.9427,14.6155,...,2.9057,9.7905,1.6704,1.6858,21.6042,3.1417,-6.5213,8.2675,14.7222,0.3965
3,train_3,0,11.0604,-2.1518,8.9522,7.1957,12.5846,-1.8361,5.8428,14.9250,...,4.4666,4.7433,0.7178,1.4214,23.0347,-1.2706,-2.9275,10.2922,17.9697,-8.9996
4,train_4,0,9.8369,-1.4834,12.8746,6.6375,12.2772,2.4486,5.9405,19.2514,...,-1.4905,9.5214,-0.1508,9.1942,13.2876,-1.5121,3.9267,9.5031,17.9974,-8.8104

In [22]:
data.shape

(200000, 202)

In [23]:
data['target'].value_counts()

target
0    179902
1     20098
Name: count, dtype: int64

In [24]:
#Checking the NUll values
data.isnull().sum()

ID_code    0
target     0
var_0      0
var_1      0
var_2      0
          ..
var_195    0
var_196    0
var_197    0
var_198    0
var_199    0
Length: 202, dtype: int64

In [25]:
data.describe()

,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,...,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,0.100490,10.679914,-1.627622,10.715192,6.796529,11.078333,-5.065317,5.408949,16.545850,0.284162,...,3.234440,7.438408,1.927839,3.331774,17.993784,-0.142088,2.303335,8.908158,15.870720,-3.326537
std,0.300653,3.040051,4.050044,2.640894,2.043319,1.623150,7.863267,0.866607,3.418076,3.332634,...,4.559922,3.023272,1.478423,3.992030,3.135162,1.429372,5.454369,0.921625,3.010945,10.438015
min,0.000000,0.408400,-15.043400,2.117100,-0.040200,5.074800,-32.562600,2.347300,5.349700,-10.505500,...,-14.093300,-2.691700,-3.814500,-11.783400,8.694400,-5.261000,-14.209600,5.960600,6.299300,-38.852800
25%,0.000000,8.453850,-4.740025,8.722475,5.254075,9.883175,-11.200350,4.767700,13.943800,-2.317800,...,-0.058825,5.157400,0.889775,0.584600,15.629800,-1.170700,-1.946925,8.252800,13.829700,-11.208475
50%,0.000000,10.524750,-1.608050,10.580000,6.825000,11.108250,-4.833150,5.385100,16.456800,0.393700,...,3.203600,7.347750,1.901300,3.396350,17.957950,-0.172700,2.408900,8.888200,15.934050,-2.819550
75%,0.000000,12.758200,1.358625,12.516700,8.324100,12.261125,0.924800,6.003000,19.102900,2.937900,...,6.406200,9.512525,2.949500,6.205800,20.396525,0.829600,6.556725,9.593300,18.064725,4.836800
max,1.000000,20.315000,10.376800,19.353000,13.188300,16.671400,17.251600,8.447700,27.691800,10.151300,...,18.440900,16.716500,8.402400,18.281800,27.928800,4.272900,18.321500,12.000400,26.079100,28.500700

In [26]:
data.head(0)

Empty DataFrame
Columns: [ID_code, target, var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11, var_12, var_13, var_14, var_15, var_16, var_17, var_18, var_19, var_20, var_21, var_22, var_23, var_24, var_25, var_26, var_27, var_28, var_29, var_30, var_31, var_32, var_33, var_34, var_35, var_36, var_37, var_38, var_39, var_40, var_41, var_42, var_43, var_44, var_45, var_46, var_47, var_48, var_49, var_50, var_51, var_52, var_53, var_54, var_55, var_56, var_57, var_58, var_59, var_60, var_61, var_62, var_63, var_64, var_65, var_66, var_67, var_68, var_69, var_70, var_71, var_72, var_73, var_74, var_75, var_76, var_77, var_78, var_79, var_80, var_81, var_82, var_83, var_84, var_85, var_86, var_87, var_88, var_89, var_90, var_91, var_92, var_93, var_94, var_95, var_96, var_97, ...]
Index: []

[0 rows x 202 columns]

In [27]:
data.duplicated().sum()

np.int64(0)

In [64]:
X=data.drop(['ID_code','target'],axis=1)
y= data["target"]

In [65]:
X.shape

(200000, 200)

In [66]:
y.shape

(200000,)

In [67]:
data.target.value_counts()

target
0    179902
1     20098
Name: count, dtype: int64

In [68]:
#Balancing the data
data_max=data[data.target==0]
data_min=data[data.target==1]

In [69]:
from sklearn.utils import resample

In [70]:
data_min_upsampled= resample(data_min,replace=True,n_samples=179902,random_state=123)
data_upsampled=pd.concat([data_max,data_min_upsampled])
data_upsampled.target.value_counts()

target
0    179902
1    179902
Name: count, dtype: int64

Now data Got Balanced

In [71]:
X=data_upsampled.iloc[:,2:]
y=data_upsampled.iloc[:,1:2]

## Model creation and checking accuracy

In [72]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=42)

In [73]:
model1= LogisticRegression()
model1.fit(X_train,y_train)

LogisticRegression()

In [74]:
pred1=model1.predict(X_test)

In [75]:
pred1

array([0, 1, 0, ..., 1, 0, 1], shape=(71961,))

In [76]:
accuracy_score(y_test,pred1)

0.7696946957379692

In [77]:
model2=RandomForestClassifier(n_estimators=50,max_depth=8,n_jobs=-1, random_state=42)

In [78]:
model2.fit(X_train,y_train)

RandomForestClassifier(max_depth=8, n_estimators=50, n_jobs=-1, random_state=42)

In [79]:
pred2=model2.predict(X_test)

In [80]:
accuracy_score(y_test,pred2)

0.7499200956073429

In [83]:
from lightgbm import LGBMClassifier

In [84]:
model3=LGBMClassifier(n_estimators=300,max_depth=8,n_jobs=-1, random_state=42)

In [85]:
model3.fit(X_train,y_train)

[LightGBM] [Info] Number of positive: 144021, number of negative: 143822
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.491908 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 51000
[LightGBM] [Info] Number of data points in the train set: 287843, number of used features: 200
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500346 -> initscore=0.001383
[LightGBM] [Info] Start training from score 0.001383

LGBMClassifier(max_depth=8, n_estimators=300, n_jobs=-1, random_state=42)

In [86]:
pred3=model3.predict(X_test)

In [87]:
accuracy_score(y_test,pred3)

0.8860632842789844

In [89]:
print("Accuracy :",accuracy_score(y_test,pred3))
print("ROC-AUC  :",roc_auc_score(y_test,pred3))
print("\nClassfication Report: \n", classification_report(y_test,pred3))

Accuracy : 0.8860632842789844
ROC-AUC  : 0.886105492156847

Classfication Report:
               precision    recall  f1-score   support

           0       0.90      0.87      0.88     36080
           1       0.87      0.90      0.89     35881

    accuracy                           0.89     71961
   macro avg       0.89      0.89      0.89     71961
weighted avg       0.89      0.89      0.89     71961

In this project multiple machine learning models were developed to predict which customers will make future transctions using the anonymized PRCP-1003 dataset. After testing Logistic Regression, Random Forest and LightGBM models, LightGBM achieved the highest accuarcy and best overall performance. It is therfore recommended as the final model for production use to help the bank identify and target potential customers are effectively.

After training and comparing multiple models -- Logisitc Regression, Random Forest and LightGBM - the LightGBM Classifier achieved the best accuracy and performance on the test data.

Hence, LightGBM is the  final recommended predictive model to help the bank  which customers  are most likely to make transctions in the future. 

This model offers:

- High Prediction Accuracy.

- Fast taining and inference speed.

- Strong performance on large, high-dimensional data.